[package]
name = "geojson_example"
version = "0.1.0"
authors = ["Michael Kirk <michael.code@endoftheworl.de>"]

[dependencies]
geojson = { version = "0.22.2", features = ["geo-types"] }
geo-types = "0.7.2"

